[vars]
  ignoreDirs = [".git", "_example", "internal"]

[metalinter]
  [metalinter.enabled]
    golint = true
    gofmt = true
    goimports = true
    varcheck = true
    aligncheck = true
    gocyclo = true
    vet = true
    deadcode = true
