[vars]
  ignoreDirs = [".git", "_example", "internal"]

[install]
  [install.goget]
    gometalinter = "github.com/alecthomas/gometalinter"
    golint = "github.com/golang/lint/golint"
    goimports = "golang.org/x/tools/cmd/goimports"
    gocyclo = "github.com/fzipp/gocyclo"
    aligncheck = "github.com/opennota/check/cmd/aligncheck"
    varcheck = "github.com/opennota/check/cmd/varcheck"

[metalinter]
  [metalinter.enabled]
    golint = true
    gofmt = true
    goimports = true
    varcheck = true
    aligncheck = true
    gocyclo = true
    vet = true
    deadcode = true
